<?xml version="1.0"?>
<package format="2">
  <name>moving_plataform_gazebo</name>
  <version>1.0.0</version>
  <description>Package with active perception experiments in Jason</description>

  <maintainer email="iagosilvestre2004@gmail.com">Iago Silvestre</maintainer>

  <license>GPLv3</license>

  <url type="website">https://github.com/natereza/moving_plataform_gazebo</url>


  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_export_depend>roscpp</build_export_depend>
  <exec_depend>roscpp</exec_depend>

  <build_depend>rospy</build_depend>
  <build_export_depend>rospy</build_export_depend>
  <exec_depend>rospy</exec_depend>

  <build_depend>gazebo_ros</build_depend>
  <build_export_depend>gazebo_ros</build_export_depend>

  <build_depend>std_msgs</build_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <exec_depend>std_msgs</exec_depend>

  <build_depend>geometry_msgs</build_depend>
  <build_export_depend>geometry_msgs</build_export_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <build_depend>gazebo_msgs</build_depend>
  <build_export_depend>gazebo_msgs</build_export_depend>
  <exec_depend>gazebo_msgs</exec_depend>

  <!--build_depend>jason_ros</build_depend>
  <build_export_depend>jason_ros</build_export_depend>
  <exec_depend>jason_ros</exec_depend>

  <build_depend>jason_ros_msgs</build_depend>
  <build_export_depend>jason_ros_msgs</build_export_depend>
  <exec_depend>jason_ros_msgs</exec_depend-->

  <exec_depend>mavros</exec_depend>
  <exec_depend>geodesy</exec_depend>
  <exec_depend>rqt_multiplot</exec_depend>
  <exec_depend>boustrophedon_msgs</exec_depend>
  <exec_depend>boustrophedon_server</exec_depend>
  <!--exec_depend>cob_people_object_detection_tensorflow</exec_depend-->

  <export>
    <gazebo_ros plugin_path="${prefix}/../../lib" gazebo_media_path="${prefix}" />
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
  </export>
</package>
